// The puzzle bank. Every answer is unique across all pools (tests/puzzles.test.ts).
//
// Pools:
//   main   - toss-ups, main rounds and tiebreakers
//   prize  - Round 3 Prize Puzzles, each tied to the trip it awards
//   triple - Triple Toss-Up sets: three puzzles that share a hidden theme
//   bonus  - short Bonus Round puzzles
//
// Denton, Texas entries were checked against current local sources (October 2026).
// Businesses whose current status could not be confirmed were left out.

import { hashId, normalize } from '../engine/answer';
import type { Category, Difficulty, Pool, Puzzle, TripleSet } from '../engine/types';

type Row = [answer: string, difficulty: Difficulty];
const E: Difficulty = 'easy';
const M: Difficulty = 'medium';
const H: Difficulty = 'hard';

const make = (pool: Pool, category: Category, [answer, difficulty]: Row): Puzzle => ({
  id: `${pool[0]}${hashId(normalize(answer))}`,
  category,
  answer,
  difficulty,
  pool,
});

/**
 * Before & After: the last word(s) of `a` are the first word(s) of `b`, and the
 * shared part appears once. `ba('COUCH POTATO', 'POTATO SALAD')` -> COUCH POTATO SALAD.
 * Throws if the halves do not overlap on whole words.
 */
export function ba(a: string, b: string): string {
  const aw = a.split(' ');
  for (let k = Math.min(aw.length - 1, 3); k >= 1; k--) {
    const shared = aw.slice(aw.length - k).join(' ');
    const next = b.charAt(shared.length);
    if (b.startsWith(shared) && (next === ' ' || next === '-')) return a + b.slice(shared.length);
  }
  throw new Error(`Before & After halves do not overlap: ${a} / ${b}`);
}

/** The two halves of each Before & After answer, kept for validation and the rules screen. */
export const BEFORE_AFTER_PARTS: Record<string, [string, string]> = {};
const B = (a: string, b: string, d: Difficulty): Row => {
  const answer = ba(a, b);
  BEFORE_AFTER_PARTS[answer] = [a, b];
  return [answer, d];
};

const MAIN: Record<Category, Row[]> = {
  Phrase: [
    ['PIECE OF CAKE', E],
    ['HOME SWEET HOME', E],
    ['LONG TIME NO SEE', E],
    ['TAKE IT EASY', E],
    ['NO PAIN NO GAIN', E],
    ['SLEEP ON IT', E],
    ['BETTER LATE THAN NEVER', E],
    ['PRACTICE MAKES PERFECT', E],
    ["TIME FLIES WHEN YOU'RE HAVING FUN", E],
    ['THE MORE THE MERRIER', E],
    ['GOOD AS NEW', E],
    ['WHAT GOES AROUND COMES AROUND', M],
    ['ACTIONS SPEAK LOUDER THAN WORDS', M],
    ['THE EARLY BIRD CATCHES THE WORM', M],
    ["DON'T COUNT YOUR CHICKENS BEFORE THEY HATCH", M],
    ['A PENNY FOR YOUR THOUGHTS', M],
    ['EVERY CLOUD HAS A SILVER LINING', M],
    ["LET'S CALL IT A DAY", M],
    ['THE BALL IS IN YOUR COURT', M],
    ['BACK TO SQUARE ONE', M],
    ['ON CLOUD NINE', M],
    ['HIT THE NAIL ON THE HEAD', M],
    ['UNDER THE WEATHER', M],
    ['A DIME A DOZEN', H],
    ["QUIT WHILE YOU'RE AHEAD", H],
    ['THE PROOF IS IN THE PUDDING', H],
    ['BITE OFF MORE THAN YOU CAN CHEW', H],
    ['ADD INSULT TO INJURY', H],
    ['JUMP THE GUN', H],
    ['BURNING THE MIDNIGHT OIL', H],
    ['THE WHOLE KIT AND CABOODLE', H],
    ['BARKING UP THE WRONG TREE', H],
    ['SIX OF ONE HALF A DOZEN OF THE OTHER', H],
    ['CROSS THAT BRIDGE WHEN YOU COME TO IT', H],
  ],
  'Food & Drink': [
    ['PEANUT BUTTER AND JELLY', E],
    ['CHOCOLATE CHIP COOKIES', E],
    ['FRENCH FRIES', E],
    ['SCRAMBLED EGGS AND BACON', E],
    ['HOT FUDGE SUNDAE', E],
    ['ICED COFFEE', E],
    ['PEPPERONI PIZZA', E],
    ['GRILLED CHEESE SANDWICH', E],
    ['STRAWBERRY MILKSHAKE', E],
    ['MACARONI AND CHEESE', E],
    ['CORN ON THE COB', E],
    ['BUTTERMILK PANCAKES WITH MAPLE SYRUP', M],
    ['CHICKEN FRIED STEAK WITH CREAM GRAVY', M],
    ['BREAKFAST TACOS', M],
    ['FRESHLY SQUEEZED ORANGE JUICE', M],
    ['SPAGHETTI AND MEATBALLS', M],
    ['CHIPS AND QUESO', M],
    ['BLUEBERRY MUFFINS', M],
    ['PINEAPPLE UPSIDE-DOWN CAKE', M],
    ['SWEET TEA WITH LEMON', M],
    ['SLOW-SMOKED BRISKET', M],
    ['GARLIC BREAD', M],
    ['JALAPENO CHEDDAR CORNBREAD', H],
    ['PUMPKIN SPICE LATTE', H],
    ['KEY LIME PIE', H],
    ['SHRIMP AND GRITS', H],
    ['CHICKEN TIKKA MASALA', H],
    ['EGGPLANT PARMESAN', H],
    ['BUFFALO CHICKEN WINGS', H],
    ['ZUCCHINI BREAD', H],
    ['SPARKLING WATER WITH A TWIST OF LIME', H],
    ['FRIED GREEN TOMATOES', H],
    ['BANANAS FOSTER', H],
  ],
  'What Are You Doing?': [
    ['TAKING A NAP', E],
    ['WALKING THE DOG', E],
    ['WATCHING A MOVIE', E],
    ['MAKING BREAKFAST', E],
    ['READING A GOOD BOOK', E],
    ['DANCING IN THE KITCHEN', E],
    ['PLAYING CARDS', E],
    ['SINGING IN THE SHOWER', E],
    ['TAKING A SELFIE', E],
    ['RIDING A BIKE', E],
    ['BAKING COOKIES', E],
    ['BINGE-WATCHING A NEW SERIES', M],
    ['ORDERING TAKEOUT', M],
    ['PARALLEL PARKING', M],
    ['PACKING FOR A ROAD TRIP', M],
    ['ROASTING MARSHMALLOWS', M],
    ['FOLDING THE LAUNDRY', M],
    ['WORKING FROM HOME', M],
    ['SHOPPING FOR GROCERIES', M],
    ['STRETCHING BEFORE A JOG', M],
    ['SLEEPING IN ON A SATURDAY', M],
    ['PLANTING A VEGETABLE GARDEN', M],
    ['JUGGLING TOO MANY THINGS AT ONCE', H],
    ['ASSEMBLING FLAT-PACK FURNITURE', H],
    ['SQUEEZING INTO SKINNY JEANS', H],
    ['HOSTING A KARAOKE NIGHT', H],
    ['UNTANGLING HOLIDAY LIGHTS', H],
    ['KAYAKING DOWN A LAZY RIVER', H],
    ['SKIPPING STONES ACROSS A POND', H],
    ['HAGGLING AT A FLEA MARKET', H],
    ['WAXING THE CAR', H],
    ['TIPTOEING DOWN THE STAIRS', H],
    ['BUZZING IN FOR A TOSS-UP', H],
  ],
  'Around the House': [
    ['KITCHEN TABLE', E],
    ['LIVING ROOM COUCH', E],
    ['WASHING MACHINE', E],
    ['FRONT PORCH SWING', E],
    ['BATHROOM MIRROR', E],
    ['COFFEE MAKER', E],
    ['TOASTER OVEN', E],
    ['BUNK BEDS', E],
    ['REMOTE CONTROL', E],
    ['WELCOME MAT', E],
    ['REFRIGERATOR MAGNETS', E],
    ['CEILING FAN', M],
    ['JUNK DRAWER', M],
    ['SMOKE DETECTOR', M],
    ['LINEN CLOSET', M],
    ['THROW PILLOWS', M],
    ['DISHWASHER', M],
    ['BACKYARD GRILL', M],
    ['GARAGE DOOR OPENER', M],
    ['LAUNDRY BASKET', M],
    ['SPICE RACK', M],
    ['ELECTRIC BLANKET', M],
    ['WALK-IN PANTRY', H],
    ['SLOW COOKER', H],
    ['MEDICINE CABINET', H],
    ['FIREPLACE MANTEL', H],
    ['KNICKKNACKS ON A BOOKSHELF', H],
    ['WINDOW BLINDS', H],
    ['CLAW-FOOT BATHTUB', H],
    ['BABY MONITOR', H],
    ['PROGRAMMABLE THERMOSTAT', H],
    ['CHANDELIER OVER THE DINING TABLE', H],
    ['QUILTED BEDSPREAD', H],
  ],
  'On the Map': [
    ['NEW YORK CITY', E],
    ['GRAND CANYON', E],
    ['LAS VEGAS NEVADA', E],
    ['NIAGARA FALLS', E],
    ['PARIS FRANCE', E],
    ['MOUNT RUSHMORE', E],
    ['ROCKY MOUNTAINS', E],
    ['SAN ANTONIO TEXAS', E],
    ['MIAMI BEACH', E],
    ['CHICAGO ILLINOIS', E],
    ['THE STATUE OF LIBERTY', E],
    ['YELLOWSTONE NATIONAL PARK', M],
    ['MISSISSIPPI RIVER', M],
    ['GOLDEN GATE BRIDGE', M],
    ['NEW ORLEANS LOUISIANA', M],
    ['LONDON ENGLAND', M],
    ['PACIFIC OCEAN', M],
    ['GREAT BARRIER REEF', M],
    ['TOKYO JAPAN', M],
    ['AMAZON RAINFOREST', M],
    ['NASHVILLE TENNESSEE', M],
    ['THE COLOSSEUM IN ROME', M],
    ['LAKE TAHOE', M],
    ['MACHU PICCHU', H],
    ['ZION NATIONAL PARK', H],
    ['CAPE COD MASSACHUSETTS', H],
    ['ALBUQUERQUE NEW MEXICO', H],
    ['AMSTERDAM NETHERLANDS', H],
    ['KEY WEST FLORIDA', H],
    ['SAHARA DESERT', H],
    ['REYKJAVIK ICELAND', H],
    ['CHESAPEAKE BAY', H],
    ['JACKSON HOLE WYOMING', H],
    ['MOUNT KILIMANJARO', H],
  ],
  'Show Biz': [
    ['THE WIZARD OF OZ', E],
    ['JURASSIC PARK', E],
    ['THE LION KING', E],
    ['FINDING NEMO', E],
    ['SATURDAY NIGHT LIVE', E],
    ['HARRY POTTER', E],
    ['THE PRICE IS RIGHT', E],
    ['SESAME STREET', E],
    ['AMERICAN IDOL', E],
    ['JEOPARDY!', E],
    ['BACK TO THE FUTURE', M],
    ['THE PRINCESS BRIDE', M],
    ['GOOD MORNING AMERICA', M],
    ['THE FRESH PRINCE OF BEL-AIR', M],
    ['STRANGER THINGS', M],
    ["GREY'S ANATOMY", M],
    ['THE GREAT BRITISH BAKING SHOW', M],
    ['RAIDERS OF THE LOST ARK', M],
    ['PURPLE RAIN', M],
    ['THE EMPIRE STRIKES BACK', M],
    ['DANCING WITH THE STARS', M],
    ['WHO WANTS TO BE A MILLIONAIRE', H],
    ['THE SHAWSHANK REDEMPTION', H],
    ['CLOSE ENCOUNTERS OF THE THIRD KIND', H],
    ["FERRIS BUELLER'S DAY OFF", H],
    ['THE SILENCE OF THE LAMBS', H],
    ['TO KILL A MOCKINGBIRD', H],
    ["BREAKFAST AT TIFFANY'S", H],
    ['THE QUEEN OF SOUL ARETHA FRANKLIN', H],
    ["MICHAEL JACKSON'S THRILLER", H],
    ['KEEPING UP WITH THE KARDASHIANS', H],
    ["WHAT'S LOVE GOT TO DO WITH IT", H],
  ],
  'Fun & Games': [
    ['HIDE-AND-SEEK', E],
    ['TIC-TAC-TOE', E],
    ['SIMON SAYS', E],
    ['MUSICAL CHAIRS', E],
    ['JUMP ROPE', E],
    ['ROCK PAPER SCISSORS', E],
    ['DUCK DUCK GOOSE', E],
    ['A GAME OF CHECKERS', E],
    ['CONNECT FOUR', E],
    ['HOT POTATO', E],
    ['THUMB WRESTLING', E],
    ['CROSSWORD PUZZLE', M],
    ['TRIVIA NIGHT', M],
    ['BOWLING ALLEY', M],
    ['HOPSCOTCH', M],
    ['JIGSAW PUZZLE', M],
    ['THREE-POINT SHOT', M],
    ['MINIATURE GOLF COURSE', M],
    ['PICKLEBALL TOURNAMENT', M],
    ['CHARADES', M],
    ['SCRABBLE TILES', M],
    ['FREE THROW LINE', M],
    ['PIN THE TAIL ON THE DONKEY', H],
    ['RED LIGHT GREEN LIGHT', H],
    ['WHITE ELEPHANT GIFT EXCHANGE', H],
    ['FANTASY FOOTBALL DRAFT', H],
    ['JENGA TOWER', H],
    ['SKEE-BALL MACHINE', H],
    ['AIR HOCKEY TABLE', H],
    ['QUARTERBACK SNEAK', H],
    ['SUDOKU PUZZLE BOOK', H],
    ['BACKGAMMON BOARD', H],
    ['A ROUND OF CORNHOLE', H],
  ],
  'Before & After': [
    B('COUCH POTATO', 'POTATO SALAD', E),
    B('PEANUT BUTTER', 'BUTTER KNIFE', E),
    B('FIRE TRUCK', 'TRUCK STOP', E),
    B('BIRTHDAY PARTY', 'PARTY ANIMAL', E),
    B('ICE CREAM', 'CREAM CHEESE', E),
    B('FISH TANK', 'TANK TOP', E),
    B('CORN DOG', 'DOG PARK', E),
    B('MUSIC VIDEO', 'VIDEO GAME', E),
    B('TABLE TENNIS', 'TENNIS BALL', E),
    B('POLAR BEAR', 'BEAR HUG', E),
    B('APPLE PIE', 'PIE CHART', E),
    B('SWEET TOOTH', 'TOOTH FAIRY', M),
    B('SHOOTING STAR', 'STAR WARS', M),
    B('FAMILY TREE', 'TREE HOUSE', M),
    B('TRAFFIC LIGHT', 'LIGHT BULB', M),
    B('SPACE STATION', 'STATION WAGON', M),
    B('SNOW WHITE', 'WHITE HOUSE', M),
    B('BABY SHOWER', 'SHOWER CURTAIN', M),
    B('COFFEE TABLE', 'TABLE MANNERS', M),
    B('WATER PARK', 'PARK BENCH', M),
    B('LUNCH BOX', 'BOX OFFICE', M),
    B('PIGGY BANK', 'BANK ACCOUNT', M),
    B('TOY STORY', 'STORY TIME', M),
    B('SPRING BREAK', 'BREAK DANCE', M),
    B('BEACH BALL', 'BALL GOWN', M),
    B('GOLF CLUB', 'CLUB SANDWICH', M),
    B('WHEEL OF FORTUNE', 'FORTUNE COOKIE', H),
    B('BANANA SPLIT', 'SPLIT DECISION', H),
    B('MOTHER GOOSE', 'GOOSE BUMPS', H),
    B('BASKETBALL COURT', 'COURT JESTER', H),
    B('DOUBLE DUTCH', 'DUTCH OVEN', H),
    B('BLACK FRIDAY', 'FRIDAY NIGHT LIGHTS', H),
    B('COWBOY HAT', 'HAT TRICK', H),
    B('GARAGE SALE', 'SALE PRICE', H),
    B('BURGER KING', 'KING-SIZE BED', H),
    B('GRAND SLAM', 'SLAM DUNK', H),
    B('HOME RUN', 'RUN FOR YOUR LIFE', H),
    B('STRAWBERRY JAM', 'JAM SESSION', H),
    B('CINNAMON ROLL', 'ROLL CALL', H),
    B('SILVER SCREEN', 'SCREEN DOOR', H),
  ],
  'Denton, Texas': [
    ['STROLLING AROUND THE DOWNTOWN SQUARE', E],
    ['UNIVERSITY OF NORTH TEXAS', E],
    ["TEXAS WOMAN'S UNIVERSITY", E],
    ['CHEERING ON THE MEAN GREEN', E],
    ['THE DENTON COUNTY COURTHOUSE', E],
    ['TAKING PHOTOS IN FRONT OF THE COURTHOUSE', E],
    ['LIVE MUSIC ON THE SQUARE', E],
    ['WALKING TO CLASS AT UNT', E],
    ["ICE CREAM AT BETH MARIE'S ON THE SQUARE", M],
    ['BROWSING THE STACKS AT RECYCLED BOOKS', M],
    ['TWILIGHT TUNES ON THE COURTHOUSE LAWN', M],
    ['THE DENTON ARTS AND JAZZ FESTIVAL', M],
    ['NORTH TEXAS FAIR AND RODEO', M],
    ['THE LITTLE CHAPEL IN THE WOODS', M],
    ['SATURDAY MORNING AT THE COMMUNITY MARKET', M],
    ['THE DAY OF THE DEAD FESTIVAL', M],
    ['CAMPING AT RAY ROBERTS LAKE', M],
    ['BRUNCH AT SEVEN MILE CAFE', M],
    ['HANGING OUT ON FRY STREET', M],
    ['LIVING IT UP IN LITTLE D', M],
    ['SCRAPPY THE EAGLE', M],
    ['A BIG PURPLE BOOKSTORE ON THE SQUARE', H],
    ['LISTENING TO JAZZ IN QUAKERTOWN PARK', H],
    ["CATCHING A SHOW AT DAN'S SILVERLEAF", H],
    ['COFFIN RACES DOWN HICKORY STREET', H],
    ["THE ONE O'CLOCK LAB BAND", H],
    ['RIDING THE A-TRAIN TO TRINITY MILLS', H],
    ['THE COURTHOUSE ON THE SQUARE MUSEUM', H],
    ['USED BOOKS IN A HISTORIC OPERA HOUSE', H],
  ],
};

type PrizeRow = [Category, string, Difficulty, string, number];
// The trip stays hidden until the puzzle is solved, as on the show.
const PRIZE: PrizeRow[] = [
  ['What Are You Doing?', 'SNORKELING IN CRYSTAL-CLEAR WATER', M, 'Trip to Cozumel, Mexico', 7850],
  ['What Are You Doing?', 'WATCHING THE NORTHERN LIGHTS', M, 'Trip to Reykjavik, Iceland', 9400],
  ['What Are You Doing?', 'RIDING A GONDOLA THROUGH THE CANALS', H, 'Trip to Venice, Italy', 9650],
  ['What Are You Doing?', 'HIKING THROUGH RED ROCK CANYONS', M, 'Trip to Sedona, Arizona', 6300],
  ['What Are You Doing?', 'SURFING THE WAVES AT SUNRISE', E, 'Trip to Maui, Hawaii', 8600],
  ['What Are You Doing?', 'SKIING DOWN A SNOWY MOUNTAIN', E, 'Ski trip to Aspen, Colorado', 7400],
  ['What Are You Doing?', 'ZIP-LINING THROUGH A RAINFOREST', H, 'Trip to Costa Rica', 7200],
  ['Food & Drink', 'BEIGNETS AND CAFE AU LAIT', H, 'Trip to New Orleans, Louisiana', 5200],
  ['Food & Drink', 'FRESH PASTA AND A GLASS OF CHIANTI', M, 'Trip to Tuscany, Italy', 9900],
  ['Food & Drink', 'FISH TACOS BY THE OCEAN', E, 'Trip to San Diego, California', 5800],
  ['Food & Drink', 'LOBSTER ROLLS ON THE COAST OF MAINE', M, 'Trip to Portland, Maine', 6100],
  ['On the Map', 'THE EIFFEL TOWER AND THE LOUVRE', E, 'Trip to Paris, France', 9800],
  ['On the Map', 'BIG BEN AND BUCKINGHAM PALACE', M, 'Trip to London, England', 9200],
  ['Show Biz', 'THE HOLLYWOOD WALK OF FAME', E, 'Trip to Los Angeles, California', 6500],
  ['Phrase', 'WISH YOU WERE HERE', E, 'Trip to Key West, Florida', 6800],
  ['Phrase', 'HAVE A NICE TRIP', E, 'Trip to Orlando, Florida', 6400],
  ['Fun & Games', 'A ROUND OF GOLF BY THE SEA', M, 'Golf getaway to Pebble Beach, California', 8900],
  ['Around the House', 'A CRACKLING FIREPLACE', E, 'Cabin getaway in Breckenridge, Colorado', 5900],
];

type TripleRow = [Category, string, Difficulty, [string, string, string]];
const TRIPLE: TripleRow[] = [
  ['Food & Drink', 'Breakfast favorites', E, ['CINNAMON TOAST', 'BLUEBERRY WAFFLES', 'CRISPY HASH BROWNS']],
  ['Around the House', 'Kitchen tools', E, ['MEASURING SPOONS', 'ROLLING PIN', 'CAN OPENER']],
  ['On the Map', 'National park destinations', M, ['YOSEMITE VALLEY', 'THE FLORIDA EVERGLADES', 'THE GREAT SMOKY MOUNTAINS']],
  ['Show Biz', 'Pixar movies', E, ['THE INCREDIBLES', 'INSIDE OUT', 'MONSTERS, INC.']],
  ['Fun & Games', 'Classic board games', E, ['CANDY LAND', 'CHUTES AND LADDERS', 'TRIVIAL PURSUIT']],
  ['What Are You Doing?', 'A day at the beach', M, ['BUILDING A SANDCASTLE', 'APPLYING SUNSCREEN', 'COLLECTING SEASHELLS']],
  ['Phrase', 'Weather expressions', M, ['TAKE A RAIN CHECK', 'THE CALM BEFORE THE STORM', 'BREAK THE ICE']],
  ['Food & Drink', 'Tex-Mex night', E, ['SIZZLING FAJITAS', 'CHEESE ENCHILADAS', 'FRESH GUACAMOLE']],
  ['Show Biz', 'Classic sitcoms', M, ['THE BIG BANG THEORY', 'MODERN FAMILY', 'HAPPY DAYS']],
  ['Around the House', 'In the bedroom', M, ['ALARM CLOCK', 'FITTED SHEET', 'BEDSIDE LAMP']],
  ['On the Map', 'European capitals', M, ['MADRID SPAIN', 'BERLIN GERMANY', 'DUBLIN IRELAND']],
  ['Fun & Games', 'Baseball', H, ['SEVENTH-INNING STRETCH', 'BOTTOM OF THE NINTH', 'STOLEN BASE']],
  ['What Are You Doing?', 'Holiday traditions', E, ['DECORATING THE TREE', 'CARVING A PUMPKIN', 'HUNTING FOR EASTER EGGS']],
  ['Phrase', 'Animal expressions', M, ['LET THE CAT OUT OF THE BAG', 'HOLD YOUR HORSES', 'WHEN PIGS FLY']],
  ['Food & Drink', 'Southern desserts', E, ['BANANA PUDDING', 'PEACH COBBLER', 'PECAN PIE']],
  ['Show Biz', 'Music legends', M, ['ELVIS PRESLEY', 'DOLLY PARTON', 'STEVIE WONDER']],
  ['On the Map', 'Texas cities', H, ['EL PASO', 'CORPUS CHRISTI', 'AMARILLO']],
  ['What Are You Doing?', 'Game night', H, ['SHUFFLING THE DECK', 'ROLLING THE DICE', 'KEEPING SCORE']],
];

const BONUS: Record<Category, Row[]> = {
  Phrase: [
    ['GOOD CALL', M],
    ['BIG DEAL', M],
    ['JUST KIDDING', E],
    ['FAIR ENOUGH', M],
    ['NO PROBLEM', E],
    ['QUICK FIX', H],
    ['TRUE STORY', M],
  ],
  'Food & Drink': [
    ['BAKED ZITI', H],
    ['FRUIT PUNCH', M],
    ['WAFFLE CONE', M],
    ['BEEF JERKY', H],
    ['CHICKEN POT PIE', E],
    ['HOT COCOA', M],
    ['GRAPE SODA', H],
  ],
  'What Are You Doing?': [
    ['FLIPPING BURGERS', E],
    ['BUYING GIFTS', M],
    ['PICKING BERRIES', M],
    ['FIXING A FLAT', H],
    ['WALKING BAREFOOT', M],
    ['JOGGING UPHILL', H],
  ],
  'Around the House': [
    ['COZY QUILT', H],
    ['MOP BUCKET', H],
    ['PHOTO ALBUM', M],
    ['WICKER BASKET', H],
    ['DESK LAMP', M],
    ['SOFA CUSHION', E],
  ],
  'On the Map': [
    ['GLACIER BAY', H],
    ['PUGET SOUND', H],
    ['OZARK MOUNTAINS', M],
    ['LAKE MICHIGAN', E],
    ['DEATH VALLEY', M],
    ['PIKES PEAK', H],
  ],
  'Show Biz': [
    ['GOLDEN GLOBES', M],
    ['THE MUPPETS', E],
    ['RED CARPET', E],
    ['DRUM SOLO', H],
    ['MOVIE MUSICAL', M],
    ['JAZZ BAND', H],
  ],
  'Fun & Games': [
    ['BOCCE BALL', H],
    ['WATER POLO', M],
    ['POKER CHIPS', M],
    ['GO FISH', H],
    ['PING-PONG PADDLE', M],
    ['FLAG FOOTBALL', E],
  ],
  'Before & After': [
    B('HOT DOG', 'DOG BOWL', M),
    B('JUNK FOOD', 'FOOD COURT', M),
    B('MOON BOOT', 'BOOT CAMP', H),
    B('BUS STOP', 'STOP SIGN', E),
    B('SUN HAT', 'HAT RACK', H),
    B('FIRE DRILL', 'DRILL BIT', H),
  ],
  'Denton, Texas': [
    ['MEAN GREEN', M],
    ['JAZZ FEST', H],
    ['QUAKERTOWN PARK', M],
    ['HICKORY STREET', H],
  ],
};

export const MAIN_PUZZLES: Puzzle[] = Object.entries(MAIN).flatMap(([cat, rows]) =>
  rows.map((r) => make('main', cat as Category, r)),
);

export const PRIZE_PUZZLES: Puzzle[] = PRIZE.map(([cat, answer, d, label, value]) => ({
  ...make('prize', cat, [answer, d]),
  prize: { label, value },
}));

export const TRIPLE_SETS: TripleSet[] = TRIPLE.map(([category, theme, difficulty, answers]) => {
  const id = `t${hashId(theme)}`;
  return {
    id,
    category,
    theme,
    difficulty,
    puzzles: answers.map((a) => ({ ...make('triple', category, [a, difficulty]), set: id, theme })),
  };
});

export const BONUS_PUZZLES: Puzzle[] = Object.entries(BONUS).flatMap(([cat, rows]) =>
  rows.map((r) => make('bonus', cat as Category, r)),
);

export const ALL_PUZZLES: Puzzle[] = [
  ...MAIN_PUZZLES,
  ...PRIZE_PUZZLES,
  ...TRIPLE_SETS.flatMap((s) => s.puzzles),
  ...BONUS_PUZZLES,
];

const BY_ID = new Map(ALL_PUZZLES.map((p) => [p.id, p]));
export const puzzleById = (id: string) => BY_ID.get(id);
export const tripleById = (id: string) => TRIPLE_SETS.find((s) => s.id === id);
